20240429-23:53:26.943 : connected
20240429-23:53:31.767 : Error on Session 'FIX.4.4:EXECUTOR->CLIENT1': System.IO.IOException: Unable to write data to the transport connection: Foi forçado o cancelamento de uma conexão existente pelo host remoto..
 ---> System.Net.Sockets.SocketException (10054): Foi forçado o cancelamento de uma conexão existente pelo host remoto.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at QuickFix.SocketReader.Send(String data)
   at QuickFix.ClientHandlerThread.Send(String data)
   at QuickFix.Session.Send(String message)
   at QuickFix.Session.SendRaw(Message message, UInt64 seqNum)
   at QuickFix.Session.GenerateBusinessMessageReject(Message message, Int32 err, Int32 field)
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
   at QuickFix.SocketReader.OnMessageFound(String msg)
20240429-23:53:31.769 : SocketReader Error: Socket exception (127.0.0.1:60825): Foi forçado o cancelamento de uma conexão existente pelo host remoto.
20240429-23:53:31.769 : shutdown requested: Disconnected
20240429-23:53:31.772 : shutdown requested: Foi forçado o cancelamento de uma conexão existente pelo host remoto.
20240429-23:53:31.772 : shutdown
